# Generated by Django 4.1.1 on 2022-09-09 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
